# Generated by Django 5.2.8 on 2025-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.FloatField()),
            ],
        ),
    ]
